apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: platform-lab
spec:
  type: ClusterIP
  selector:
    app: platform-lab
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: metrics
      port: 9464
      targetPort: 9464